# Generated by Django 3.2.9 on 2021-12-01 10:43

import Employee.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(max_length=120)),
                ('location', models.CharField(max_length=120)),
                ('information', models.TextField(blank=True, max_length=500, null=True)),
                ('phone_no', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=120)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auth.group')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('gender', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=150)),
                ('father_name', models.CharField(max_length=150)),
                ('mother_name', models.CharField(max_length=150)),
                ('join_date', models.DateField()),
                ('pan_no', models.CharField(max_length=120, null=True)),
                ('contact_no', models.CharField(max_length=20)),
                ('left_date', models.DateField(null=True)),
                ('goods_provided', models.CharField(max_length=200, null=True)),
                ('reference_by', models.CharField(max_length=120, null=True)),
                ('bio', models.TextField(max_length=500, null=True)),
                ('photo', models.ImageField(upload_to=Employee.models.upload_location)),
                ('passport_or_citizenship', models.ImageField(upload_to=Employee.models.upload_location)),
                ('family_photo', models.ImageField(blank=True, null=True, upload_to=Employee.models.upload_location)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Employee.branch')),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Employee.designation')),
            ],
        ),
    ]
